services:
  - type: web
    name: telegram-bot
    env: python
    region: singapore
    buildCommand: |
      mkdir -p data/messages
      pip install -r requirements.txt
    startCommand: python -m src.main
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.10
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: PHONE_NUMBER
        sync: false      - key: SESSION_STRING
        sync: false
    autoDeploy: true
